export const FETCH_PUB_REPOS_REQUEST = 'FETCH_PUB_REPOS_REQUEST';
export const FETCH_PUB_REPOS_SUCCESS = 'FETCH_PUB_REPOS_SUCCESS';
export const FETCH_PUB_REPOS_FAILURE = 'FETCH_PUB_REPOS_FAILURE';

export const FETCH_PERS_REPOS_REQUEST = 'FETCH_PERS_REPOS_REQUEST';
export const FETCH_PERS_REPOS_SUCCESS = 'FETCH_PERS_REPOS_SUCCESS';
export const FETCH_PERS_REPOS_FAILURE = 'FETCH_PERS_REPOS_FAILURE';
